### PR TITLE
[2.4] fix minimatch version

### PR DESCRIPTION
**Pull request by zlayne**
Signed-off-by: Zack Layne <zlayne@redhat.com>

**Related Issue:**  stolostron/backlog#26438

### Description of changes
- updated prod minimatch versions where possible.

### CODE REVIEW

**Comment by SherinV** [comment]
Looks like there is one more at 3.0.4. I am not sure if we can update that. 

```
➜  search-ui git:(fix-minimatch-version) ✗ npm ls minimatch
@stolostron/search-ui@2.4.0 /Users/shvarugh/Documents/Github/go/src/github.com/open-cluster-management/search-ui
├─┬ @kubernetes/client-node@0.17.1
│ └─┬ shelljs@0.8.5
│   └─┬ glob@7.2.3
│     └── minimatch@3.1.2
└─┬ serve@14.0.1
  └─┬ serve-handler@6.1.3
    └── minimatch@3.0.4
```

**Comment by zlayne** [comment]
> Looks like there is one more at 3.0.4. I am not sure if we can update that.
> 
> ```
> ➜  search-ui git:(fix-minimatch-version) ✗ npm ls minimatch
> @stolostron/search-ui@2.4.0 /Users/shvarugh/Documents/Github/go/src/github.com/open-cluster-management/search-ui
> ├─┬ @kubernetes/client-node@0.17.1
> │ └─┬ shelljs@0.8.5
> │   └─┬ glob@7.2.3
> │     └── minimatch@3.1.2
> └─┬ serve@14.0.1
>   └─┬ serve-handler@6.1.3
>     └── minimatch@3.0.4
> ```

No I updated the serve package to latest, but it still does not require the fixed version on minimatch.

**Review by SherinV — APPROVED** [review]

**Comment by zlayne** [comment]
Will merge once 2.4.z is open

**Comment by zlayne** [comment]
2.4 is EOL - closing

**Pull request closed without merging**
